kind: Service
apiVersion: v1
metadata:
  name: sandbox
  labels:
    app: sandbox
spec:
  selector:
    app: sandbox
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30001
  #type: ClusterIP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
spec:
  selector:
      matchLabels:
        app: sandbox
        tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: sandbox
        tier: backend
    spec:
      containers:
        - name: sandbox
          image: mmorenoalvariza/sandbox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
